[package]
edition.workspace      = true
license.workspace      = true
name                   = "xtask"
publish                = false
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow           = { features = ["std"], workspace = true }
clap             = { features = ["derive"], workspace = true }
toml             = { workspace = true }
tree-sitter      = { version = "0.26" }
tree-sitter-rust = { version = "0.24" }
